version: '3.8'

services:
  task-manager:
    image: ghcr.io/pulkit9897/task-manager:latest
    ports:
      - "5000:5000"
    volumes:
      - task-data:/app/instance
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  task-data: